name: minimal

on:
  workflow_dispatch:
    inputs:
      runner_image_version:
        description: 'Runner Image Version (example: 20240422.1)'
        required: true
        type: string

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: Dockerfile-minimal
          build-args: RUNNER_IMAGE_VERSION=${{ inputs.runner_image_version }}
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/sprinters-sh/sprinters-image-full-ubuntu22:latest
            ghcr.io/sprinters-sh/sprinters-image-full-ubuntu22:${{ inputs.runner_image_version }}
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=sprinters.sh runner,annotation-index.org.opencontainers.image.licenses=MIT,annotation-index.org.opencontainers.source=https://github.com/sprinters-sh/sprinter-image
