name: minimal

on:
  workflow_dispatch:
    inputs:
      runner_version:
        description: 'Runner Version (example: 2.316.1)'
        required: true
        type: string

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile-minimal
          build-args: RUNNER_VERSION=${{ inputs.runner_version }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/sprinters-sh/sprinters-image-minimal:latest
            ghcr.io/sprinters-sh/sprinters-image-minimal:${{ inputs.runner_version }}
          outputs: type=image,name=target,annotation-index.org.opencontainers.image.description=sprinters.sh runner,annotation-index.org.opencontainers.image.licenses=MIT,annotation-index.org.opencontainers.source=https://github.com/sprinters-sh/sprinter-image
